name: Build Check

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [change]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Do makepkg
        id: makepkg
        uses: eweOS/pkgchecker-action@v1
      - name: Print Package Files
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
